SELECT setval('cashier_id_seq', coalesce(max(id),0) + 1, false) FROM cashier;
SELECT setval('cashier_log_id_seq', coalesce(max(id),0) + 1, false) FROM cashier_log;
SELECT setval('payment_method_id_seq', coalesce(max(id),0) + 1, false) FROM payment_method;
SELECT setval('payment_method_store_id_seq', coalesce(max(id),0) + 1, false) FROM payment_method_store;
SELECT setval('profession_id_seq', coalesce(max(id),0) + 1, false) FROM profession;
SELECT setval('store_id_seq', coalesce(max(id),0) + 1, false) FROM store;
SELECT setval('store_group_id_seq', coalesce(max(id),0) + 1, false) FROM store_group;
SELECT setval('user_id_seq', coalesce(max(id),0) + 1, false) FROM user;
SELECT setval('user_store_transfer_id_seq', coalesce(max(id),0) + 1, false) FROM user_store_transfer;